name: sdg4_education_app
description: A Flutter app for Quality Education (SDG 4)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  provider: ^6.0.5
  flutter_animate: ^4.2.0
  cupertino_icons: ^1.0.6
  file_selector: ^1.0.3
  permission_handler: ^11.0.1
  intl: ^0.18.0       # Added for date formatting
  firebase_storage: ^12.4.7  # Added for file storage
  http: ^1.2.0        # Added for HTTP requests to Cloudinary
  url_launcher: ^6.3.1
  flutter_pdfview: ^1.2.3
  path_provider: ^2.1.3
  open_file: ^3.2.1
  dio: ^5.3.3
  http_parser: ^4.0.2
  crypto: ^3.0.0
  jitsi_meet_wrapper: ^0.2.0+1
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true